### GET all todo items
GET http://localhost:8080/todo


### GET specific todo item
GET http://localhost:8080/todo/5e6e6261-1666-4bdf-9d85-6fd6c2b7a65e

### POST request to add a new todo item
POST http://localhost:8080/todo
Content-Type: application/json

{
 "text": "Learn how to use HTTP calls 2"
}

### DELETE todo by ID
DELETE http://localhost:8080/todo/3e10d9c1-e9d3-4c03-ac83-f85387072c7a


### POST request to add a new todo item
POST http://localhost:8080/todo/3e10d9c1-e9d3-4c03-ac83-f85387072c7a/state/true

### GET version
GET http://localhost:8080/version